<a href="https://colab.research.google.com/github/greymouse1/ss_lab1/blob/main/ss_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import numpy for matrix operations
import numpy as np
# import math for advanced operations
import math

# import modules for handling external files
import requests
from io import StringIO

Task #1

In [2]:
# define known values (everything is in meters and dgm)

# GRS80 parameters
a = 6378137
f = 1/298.257222101


# semi-minor axis
b = a*(1-f)

# ellipsoid height
h = 85

# eccentricity
e_sq = ((a**2)-(b**2))/(a**2)

# Lat
lat_d = 59
lat_m = 20
lat_s = 59

# Lon
lon_d = 18
lon_m = 4
lon_s = 10

# define functions for conversion from dgm to radians

def dgm_rad (d,m,s) :
  decimal_degrees = d + m/60 + s/3600
  print(f"Decimal degrees are {decimal_degrees}")
  degrees_radians = decimal_degrees * (math.pi / 180)
  return degrees_radians

# Lat in rads
lat_r = dgm_rad(lat_d,lat_m,lat_s)

# Long in rads
lon_r = dgm_rad(lon_d,lon_m,lon_s)

N = a / math.sqrt(1 - e_sq * math.sin(lat_r)**2)

# define functions for conversion of geodetic to cartesian coordinates
X = (N+h)*(math.cos(lat_r)*math.cos(lon_r))
Y = (N+h)*(math.cos(lat_r)*math.sin(lon_r))
Z = (N*(1-e_sq)+h)*math.sin(lat_r)

print(f"X coordinate is {X}")
print(f"Y coordinate is {Y}")
print(f"Z coordinate is {Z}")

def geocentric_geodetic(X,Y,Z,e_sq):

  # define auxiliary values
  p = math.sqrt(X**2 + Y**2)

  teta = math.atan(Z / (p*math.sqrt(1 - e_sq)))

  # define functions for conversion from cartesian to geodetic

  lon = math.degrees(math.atan(Y/X))
  lat = math.degrees(math.atan((Z + ((a*e_sq)/math.sqrt(1-e_sq))*math.sin(teta)**3) / (p - a*e_sq*math.cos(teta)**3) ))
  h_reverse = (p / math.cos(math.radians(lat))) - N

  return(lon,lat,h_reverse)

calc_values = geocentric_geodetic(X,Y,Z,e_sq)
print(calc_values)
#print(f"Longitude is {lon}")
#print(f"Latitude is {lat}")
#print(f"h is {h_reverse}")

Decimal degrees are 59.349722222222226
Decimal degrees are 18.069444444444443
X coordinate is 3098917.2417289796
Y coordinate is 1011053.4113269701
Z coordinate is 5463972.352679947
(18.069444444444443, 59.34972222222222, 84.99999999906868)


Task #2

In [23]:
# Satellite positions file path
external_link = 'https://raw.githubusercontent.com/greymouse1/ss_lab1/main/satellites.txt'

# Download data from the external link
response = requests.get(external_link)
data = np.genfromtxt(StringIO(response.text), delimiter=' ')

# Create a dictionary with satellite names as keys and coordinate vectors as values
sat_dict = {}

for row in data:
    sat_name = row[0] # Convert bytes to string for the point name
    sat_coordinates = np.array(row[1:4], dtype=float)  # Create a NumPy array for coordinates
    sat_dict[str(int(sat_name))] = 100*sat_coordinates  # Add to the dictionary

# Create rotation matrix Rl
R1 = np.array([[1, 0, 0],
               [0,math.cos(90 * (math.pi / 180)-lat_r) ,math.sin(90 * (math.pi / 180)-lat_r) ],
               [0, -1*math.sin(90 * (math.pi / 180)-lat_r),math.cos(90 * (math.pi / 180)-lat_r) ]])

R3 = np.array([[math.cos(lon_r+90 * (math.pi / 180)) ,math.sin(lon_r+90 * (math.pi / 180)), 0],
               [-1*math.sin(lon_r+90 * (math.pi / 180)),math.cos(lon_r+90 * (math.pi / 180)) , 0],
               [0, 0, 1]])

Rl = np.dot(R1,R3)

print("Rl matrix is: ", "\n" , Rl)

# Convert all satellite coordinates to ENU coordinates

sat_enu = {}

origin_vector = np.array([X, Y, Z])

for sat in sat_dict:
  sat_enu[sat] = np.dot(Rl,sat_dict[sat] - origin_vector)

# Create function for calculating azimuth

def azimuth(e,n):
  azimuth_rad = math.atan2(e, n)
  azimuth_deg = math.degrees(azimuth_rad)

  # Ensure azimuth is in the range [0, 360)
  azimuth_deg = (azimuth_deg + 360) % 360

  return azimuth_deg

enu = {}
print(sat_enu)
for sat in sat_enu:
  e = sat_enu[sat][0]
  n = sat_enu[sat][1]

  # height
  u = sat_enu[sat][2]
  # slant distance
  s = math.sqrt(n**2+e**2+u**2)

  # zenith
  z = math.degrees(math.acos(u / s))

  # elevation
  ele = 90 - z

  # pack all values
  values = [azimuth(e,n),ele,s]

  sat_enu[sat] = values


print(sat_enu)




[  -764.51 -16615.4   20301.22]
Rl matrix is:  
 [[-0.31016948  0.95068128  0.        ]
 [-0.81786636 -0.26683725  0.50979653]
 [ 0.48465402  0.15812333  0.86029501]]
{'1': array([  898524.02839606, -1714962.6486996 , -4551696.00893614]), '2': array([-1080284.17872713,   639034.18108792, -8734001.37788294]), '3': array([  297047.3909689 , -2351149.15177505, -5163147.10874703]), '4': array([-2196208.24270297,   813220.09073908, -7590094.20501241]), '5': array([ 1899993.20544329,  1804527.11811284, -6795514.30941166]), '6': array([ 1470986.8734174 ,  -459804.80416691, -8503509.16016725]), '7': array([-1402159.59086179,  2207007.71766698, -5676465.86639989]), '8': array([-2504143.9790045 ,   678768.74373407, -6850291.1996975 ]), '9': array([  994746.44748443,  2109445.87902649, -5155460.06699501]), '10': array([  217458.96467626,   640050.39625597, -8949453.12620313]), '11': array([-1.12661344e+06, -3.35334800e+02, -3.96224014e+06]), '13': array([-1404446.05174978, -1489035.56284053, -804

# New section